name: backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          pip install pytest pytest-cov sentry-sdk
          ls -lR
          pytest . --cov .
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
